import { createSlice } from "@reduxjs/toolkit";

// Create a counter slice
const counterSlice = createSlice({
  name: "counter", // The name of the slice
  initialState: 0, // Initial state of the counter
  reducers: {
    increment: (state) => state + 1, // Reducer function for incrementing the counter
    decrement: (state) => state - 1, // Reducer function for decrementing the counter
    reset: (state) => state - state, // Reducer function for resetting the counter to 0
  },
});

// Export the actions generated by the counter slice
export const { increment, decrement, reset } = counterSlice.actions;

// Export the counter reducer
export default counterSlice.reducer;
